name: 'OWASP ZAP DAST Scan'
description: 'Dynamic Application Security Testing with OWASP ZAP via Tailscale'

inputs:
  github_token:
    description: 'GitHub token for creating issues'
    required: true
  tailscale_auth_key:
    description: 'Tailscale Auth Key (reusable, ephemeral)'
    required: true
  target_url:
    description: 'Target URL to scan (e.g., http://100.105.177.39:3000)'
    required: true
  scan_type:
    description: 'Scan type: baseline or full'
    required: false
    default: 'baseline'
  fail_on_severity:
    description: 'Fail build on alerts at or above this severity (HIGH, MEDIUM, LOW)'
    required: false
    default: 'HIGH'

runs:
  using: "composite"
  steps:
    - name: Setup Tailscale
      uses: tailscale/github-action@v2
      with:
        authkey: ${{ inputs.tailscale_auth_key }}

    - name: Verify Tailscale Connection
      shell: bash
      run: |
        echo "ðŸ”— Connected to Tailscale network"
        tailscale status
        
        # Extract target host from URL
        TARGET_HOST=$(echo "${{ inputs.target_url }}" | sed -E 's|https?://([^:/]+).*|\1|')
        
        # Test connectivity
        if ping -c 3 "$TARGET_HOST" > /dev/null 2>&1; then
          echo "âœ… Target host $TARGET_HOST is reachable"
        else
          echo "âš ï¸ Warning: Cannot ping $TARGET_HOST (might still be accessible via HTTP)"
        fi

    - name: Run ZAP Baseline Scan (Docker)
      id: zap_scan
      shell: bash
      run: |
        REPORT_FILE="${{ github.workspace }}/zap-report.json"
        HTML_REPORT="${{ github.workspace }}/zap-report.html"
        TARGET_URL="${{ inputs.target_url }}"
        
        echo "ðŸ³ Pulling ZAP Docker image..."
        docker pull ghcr.io/zaproxy/zaproxy:stable
        
        if [[ "${{ inputs.scan_type }}" == "full" ]]; then
          echo "ðŸ” Running FULL ZAP scan (this may take 15-30 minutes)..."
          
          docker run --rm \
            --network host \
            -v $(pwd):/zap/wrk:rw \
            -t ghcr.io/zaproxy/zaproxy:stable \
            zap-full-scan.py \
            -t "$TARGET_URL" \
            -J zap-report.json \
            -r zap-report.html \
            -I || true
            
        else
          echo "ðŸ” Running BASELINE ZAP scan (quick security check)..."
          
          docker run --rm \
            --network host \
            -v $(pwd):/zap/wrk:rw \
            -t ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
            -t "$TARGET_URL" \
            -J zap-report.json \
            -r zap-report.html \
            -I || true
        fi
        
        # Ensure reports exist (create empty if needed)
        if [[ ! -f "$REPORT_FILE" ]]; then
          echo '{"site": [{"alerts": []}]}' > "$REPORT_FILE"
        fi
        
        if [[ ! -f "$HTML_REPORT" ]]; then
          echo "<html><body><h1>ZAP Scan - No Results</h1></body></html>" > "$HTML_REPORT"
        fi
        
        # Parse results
        if [[ -f "$REPORT_FILE" ]]; then
          HIGH_COUNT=$(jq '[.site[]?.alerts[]? | select(.riskcode == "3")] | length' "$REPORT_FILE" 2>/dev/null || echo "0")
          MEDIUM_COUNT=$(jq '[.site[]?.alerts[]? | select(.riskcode == "2")] | length' "$REPORT_FILE" 2>/dev/null || echo "0")
          LOW_COUNT=$(jq '[.site[]?.alerts[]? | select(.riskcode == "1")] | length' "$REPORT_FILE" 2>/dev/null || echo "0")
          INFO_COUNT=$(jq '[.site[]?.alerts[]? | select(.riskcode == "0")] | length' "$REPORT_FILE" 2>/dev/null || echo "0")
          TOTAL_COUNT=$((HIGH_COUNT + MEDIUM_COUNT + LOW_COUNT + INFO_COUNT))
          
          echo "high_count=$HIGH_COUNT" >> $GITHUB_OUTPUT
          echo "medium_count=$MEDIUM_COUNT" >> $GITHUB_OUTPUT
          echo "low_count=$LOW_COUNT" >> $GITHUB_OUTPUT
          echo "info_count=$INFO_COUNT" >> $GITHUB_OUTPUT
          echo "total_count=$TOTAL_COUNT" >> $GITHUB_OUTPUT
        else
          echo "high_count=0" >> $GITHUB_OUTPUT
          echo "medium_count=0" >> $GITHUB_OUTPUT
          echo "low_count=0" >> $GITHUB_OUTPUT
          echo "info_count=0" >> $GITHUB_OUTPUT
          echo "total_count=0" >> $GITHUB_OUTPUT
        fi
        
        echo "ðŸ“Š Scan complete!"
        echo "   HIGH: $HIGH_COUNT | MEDIUM: $MEDIUM_COUNT | LOW: $LOW_COUNT | INFO: $INFO_COUNT"

    - name: Generate Summary Report
      if: always()
      shell: bash
      run: |
        REPORT_FILE="${{ github.workspace }}/zap-report.json"
        
        echo "## ðŸŒ OWASP ZAP DAST Report" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Target:** ${{ inputs.target_url }}" >> $GITHUB_STEP_SUMMARY
        echo "**Scan Type:** ${{ inputs.scan_type }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### ðŸ” Security Alerts" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Total Alerts:** ${{ steps.zap_scan.outputs.total_count }}" >> $GITHUB_STEP_SUMMARY
        echo "- ðŸ”´ HIGH: ${{ steps.zap_scan.outputs.high_count }}" >> $GITHUB_STEP_SUMMARY
        echo "- ðŸŸ  MEDIUM: ${{ steps.zap_scan.outputs.medium_count }}" >> $GITHUB_STEP_SUMMARY
        echo "- ðŸŸ¡ LOW: ${{ steps.zap_scan.outputs.low_count }}" >> $GITHUB_STEP_SUMMARY
        echo "- ðŸ”µ INFO: ${{ steps.zap_scan.outputs.info_count }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [[ "${{ steps.zap_scan.outputs.total_count }}" -gt 0 ]]; then
          echo "### âš ï¸ High Risk Findings" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Risk | Alert | URL | CWE |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- | --- | --- |" >> $GITHUB_STEP_SUMMARY
          
          jq -r '.site[]?.alerts[]? | select(.riskcode == "3") | 
            "| HIGH | \(.name) | \(.url // "N/A") | \(.cweid // "N/A") |"' \
            "$REPORT_FILE" | head -n 20 >> $GITHUB_STEP_SUMMARY || true
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "_Showing top 20 HIGH risk alerts. See full report in artifacts._" >> $GITHUB_STEP_SUMMARY
        else
          echo "âœ… **No security vulnerabilities detected!**" >> $GITHUB_STEP_SUMMARY
        fi

    - name: Create GitHub Issue (HIGH Severity Only)
      if: steps.zap_scan.outputs.high_count > 0
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
        HIGH_COUNT="${{ steps.zap_scan.outputs.high_count }}"
        MEDIUM_COUNT="${{ steps.zap_scan.outputs.medium_count }}"
        TOTAL_COUNT="${{ steps.zap_scan.outputs.total_count }}"
        
        echo "## ðŸš¨ OWASP ZAP DAST Alert - Security Vulnerabilities Detected" > issue_body.md
        echo "" >> issue_body.md
        echo "**Scan:** Dynamic Application Security Testing (OWASP ZAP)" >> issue_body.md
        echo "**Severity:** HIGH" >> issue_body.md
        echo "**Target:** ${{ inputs.target_url }}" >> issue_body.md
        echo "**Scan Type:** ${{ inputs.scan_type }}" >> issue_body.md
        echo "**Triggered by:** ${{ github.event_name }} on ${{ github.ref_name }}" >> issue_body.md
        echo "" >> issue_body.md
        echo "### ðŸ” Alert Summary" >> issue_body.md
        echo "" >> issue_body.md
        echo "- **HIGH:** $HIGH_COUNT" >> issue_body.md
        echo "- **MEDIUM:** $MEDIUM_COUNT" >> issue_body.md
        echo "- **Total Alerts:** $TOTAL_COUNT" >> issue_body.md
        echo "" >> issue_body.md
        echo "### ðŸ”´ High Risk Vulnerabilities" >> issue_body.md
        echo "" >> issue_body.md
        echo '```' >> issue_body.md
        jq -r '.site[]?.alerts[]? | select(.riskcode == "3") | 
          "Alert: \(.name)\nURL: \(.url // "N/A")\nCWE: \(.cweid // "N/A")\nDescription: \(.desc // "N/A")\nSolution: \(.solution // "N/A")\n---"' \
          zap-report.json | head -n 200 >> issue_body.md
        echo '```' >> issue_body.md
        echo "" >> issue_body.md
        echo "---" >> issue_body.md
        echo "### ðŸ› ï¸ Remediation Steps" >> issue_body.md
        echo "" >> issue_body.md
        echo "1. **Review each HIGH risk alert** in the full ZAP report" >> issue_body.md
        echo "2. **Common OWASP ZAP findings:**" >> issue_body.md
        echo "   - **XSS (Cross-Site Scripting):** Sanitize all user inputs" >> issue_body.md
        echo "   - **SQL Injection:** Use parameterized queries" >> issue_body.md
        echo "   - **CSRF:** Implement anti-CSRF tokens" >> issue_body.md
        echo "   - **Missing Security Headers:** Add CSP, X-Frame-Options, etc." >> issue_body.md
        echo "   - **Insecure Authentication:** Use secure session management" >> issue_body.md
        echo "3. **Test fixes locally** before deploying to QA/Prod" >> issue_body.md
        echo "4. **Re-run ZAP scan** after implementing fixes" >> issue_body.md
        echo "" >> issue_body.md
        echo "**Workflow Run:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> issue_body.md
        
        # Check for existing open issue
        EXISTING_ISSUE=$(gh issue list --state open --search "OWASP ZAP DAST Alert in:title" --json number --jq '.[0].number' || true)
        
        if [[ -n "$EXISTING_ISSUE" ]]; then
          echo "âš ï¸ Updating existing issue #$EXISTING_ISSUE"
          gh issue comment "$EXISTING_ISSUE" --body "ðŸ”„ **Recurrence detected** in workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        else
          echo "ðŸš¨ Creating new security issue"
          gh issue create \
            --title "[HIGH] OWASP ZAP DAST Alert - $HIGH_COUNT HIGH Risk Vulnerabilities" \
            --body-file issue_body.md \
            --label "security,dast,zap,high-severity" \
            --assignee "${{ github.actor }}"
        fi

    - name: Disconnect Tailscale
      if: always()
      shell: bash
      run: |
        sudo tailscale down || true

    - name: Fail Workflow Gate
      if: |
        (inputs.fail_on_severity == 'HIGH' && steps.zap_scan.outputs.high_count > 0) ||
        (inputs.fail_on_severity == 'MEDIUM' && (steps.zap_scan.outputs.high_count > 0 || steps.zap_scan.outputs.medium_count > 0)) ||
        (inputs.fail_on_severity == 'LOW' && steps.zap_scan.outputs.total_count > 0)
      shell: bash
      run: |
        echo "::error::OWASP ZAP detected vulnerabilities at or above ${{ inputs.fail_on_severity }} severity. Build failed."
        exit 1
