name: 'Backend Security Scan (MERN)'
description: 'Full-stack SAST for Node.js/Express backend and React frontend using Semgrep and ESLint'

inputs:
  github_token:
    description: 'GitHub token for creating issues'
    required: true
  fail_on_high_critical:
    description: 'Fail the workflow if HIGH or CRITICAL vulnerabilities are found'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Setup Python (for Semgrep)
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Security Tools
      shell: bash
      run: |
        npm install -g eslint@8 eslint-plugin-security --silent
        pip install semgrep --quiet

    - name: Create ESLint Config
      shell: bash
      run: |
        cat > .eslintrc.json << 'ESLINTEOF'
{
  "env": {
    "browser": true,
    "es2021": true,
    "node": true
  },
  "extends": ["eslint:recommended"],
  "plugins": ["security"],
  "rules": {
    "security/detect-object-injection": "warn",
    "security/detect-non-literal-fs-filename": "warn",
    "security/detect-eval-with-expression": "error",
    "security/detect-no-csrf-before-method-override": "warn",
    "security/detect-buffer-noassert": "error",
    "security/detect-child-process": "warn",
    "security/detect-disable-mustache-escape": "error",
    "security/detect-new-buffer": "error",
    "security/detect-pseudoRandomBytes": "error",
    "security/detect-possible-timing-attacks": "warn",
    "security/detect-unsafe-regex": "error"
  }
}
ESLINTEOF

    - name: Run ESLint Security Scan
      id: eslint_scan
      shell: bash
      run: |
        REPORT_FILE="${{ github.workspace }}/eslint-report.json"
        
        eslint . --ext .js,.jsx,.ts,.tsx --format json --output-file "$REPORT_FILE" || true
        
        if [[ -f "$REPORT_FILE" ]]; then
          TOTAL_ISSUES=$(jq '[.[] | .messages[]] | length' "$REPORT_FILE" 2>/dev/null || echo "0")
          ERROR_COUNT=$(jq '[.[] | .messages[] | select(.severity == 2)] | length' "$REPORT_FILE" 2>/dev/null || echo "0")
          WARNING_COUNT=$(jq '[.[] | .messages[] | select(.severity == 1)] | length' "$REPORT_FILE" 2>/dev/null || echo "0")
          
          echo "eslint_total=$TOTAL_ISSUES" >> $GITHUB_OUTPUT
          echo "eslint_errors=$ERROR_COUNT" >> $GITHUB_OUTPUT
          echo "eslint_warnings=$WARNING_COUNT" >> $GITHUB_OUTPUT
        else
          echo "eslint_total=0" >> $GITHUB_OUTPUT
          echo "eslint_errors=0" >> $GITHUB_OUTPUT
          echo "eslint_warnings=0" >> $GITHUB_OUTPUT
        fi

    - name: Run Semgrep SAST
      id: semgrep_scan
      shell: bash
      run: |
        REPORT_FILE="${{ github.workspace }}/semgrep-report.json"
        
        semgrep scan \
          --config p/nodejs \
          --config p/react \
          --config p/javascript \
          --config p/typescript \
          --config p/owasp-top-10 \
          --config p/security-audit \
          --json \
          --output "$REPORT_FILE" \
          --quiet || true
        
        if [[ -f "$REPORT_FILE" ]]; then
          CRITICAL_COUNT=$(jq '[.results[] | select(.extra.severity == "CRITICAL")] | length' "$REPORT_FILE" 2>/dev/null || echo "0")
          HIGH_COUNT=$(jq '[.results[] | select(.extra.severity == "HIGH")] | length' "$REPORT_FILE" 2>/dev/null || echo "0")
          MEDIUM_COUNT=$(jq '[.results[] | select(.extra.severity == "MEDIUM")] | length' "$REPORT_FILE" 2>/dev/null || echo "0")
          LOW_COUNT=$(jq '[.results[] | select(.extra.severity == "LOW")] | length' "$REPORT_FILE" 2>/dev/null || echo "0")
          TOTAL_COUNT=$(jq '.results | length' "$REPORT_FILE" 2>/dev/null || echo "0")
          
          echo "semgrep_critical=$CRITICAL_COUNT" >> $GITHUB_OUTPUT
          echo "semgrep_high=$HIGH_COUNT" >> $GITHUB_OUTPUT
          echo "semgrep_medium=$MEDIUM_COUNT" >> $GITHUB_OUTPUT
          echo "semgrep_low=$LOW_COUNT" >> $GITHUB_OUTPUT
          echo "semgrep_total=$TOTAL_COUNT" >> $GITHUB_OUTPUT
        else
          echo "semgrep_critical=0" >> $GITHUB_OUTPUT
          echo "semgrep_high=0" >> $GITHUB_OUTPUT
          echo "semgrep_medium=0" >> $GITHUB_OUTPUT
          echo "semgrep_low=0" >> $GITHUB_OUTPUT
          echo "semgrep_total=0" >> $GITHUB_OUTPUT
        fi

    - name: Generate Summary Report
      if: always()
      shell: bash
      run: |
        echo "## ðŸ›¡ï¸ Web Stack Security Report (MERN)" >> $GITHUB_STEP_SUMMARY
        
        # Semgrep Results
        echo "### Semgrep SAST Results" >> $GITHUB_STEP_SUMMARY
        if [[ "${{ steps.semgrep_scan.outputs.semgrep_total }}" -gt 0 ]]; then
          echo "**Total Issues:** ${{ steps.semgrep_scan.outputs.semgrep_total }}" >> $GITHUB_STEP_SUMMARY
          echo "- ðŸ”´ CRITICAL: ${{ steps.semgrep_scan.outputs.semgrep_critical }}" >> $GITHUB_STEP_SUMMARY
          echo "- ðŸŸ  HIGH: ${{ steps.semgrep_scan.outputs.semgrep_high }}" >> $GITHUB_STEP_SUMMARY
          echo "- ðŸŸ¡ MEDIUM: ${{ steps.semgrep_scan.outputs.semgrep_medium }}" >> $GITHUB_STEP_SUMMARY
          echo "- ðŸŸ¢ LOW: ${{ steps.semgrep_scan.outputs.semgrep_low }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          echo "#### Top Findings:" >> $GITHUB_STEP_SUMMARY
          echo "| Severity | Rule | File:Line | Message |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- | --- | --- |" >> $GITHUB_STEP_SUMMARY
          jq -r '.results[] | select(.extra.severity == "CRITICAL" or .extra.severity == "HIGH") | 
            "| \(.extra.severity) | \(.check_id) | \(.path):\(.start.line) | \(.extra.message[:100]) |"' semgrep-report.json | head -n 20 >> $GITHUB_STEP_SUMMARY
        else
          echo "âœ… **No high-risk semantic vulnerabilities detected.**" >> $GITHUB_STEP_SUMMARY
        fi
        
        echo "" >> $GITHUB_STEP_SUMMARY
        
        # ESLint Results
        echo "### ESLint Security Results" >> $GITHUB_STEP_SUMMARY
        if [[ "${{ steps.eslint_scan.outputs.eslint_total }}" -gt 0 ]]; then
          echo "**Total Issues:** ${{ steps.eslint_scan.outputs.eslint_total }}" >> $GITHUB_STEP_SUMMARY
          echo "- Errors: ${{ steps.eslint_scan.outputs.eslint_errors }}" >> $GITHUB_STEP_SUMMARY
          echo "- Warnings: ${{ steps.eslint_scan.outputs.eslint_warnings }}" >> $GITHUB_STEP_SUMMARY
        else
          echo "âœ… **No ESLint security issues.**" >> $GITHUB_STEP_SUMMARY
        fi

    - name: Create GitHub Issue (HIGH/CRITICAL Only)
      if: |
        steps.semgrep_scan.outputs.semgrep_critical > 0 || 
        steps.semgrep_scan.outputs.semgrep_high > 0 ||
        steps.eslint_scan.outputs.eslint_errors > 0
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
        CRITICAL_COUNT="${{ steps.semgrep_scan.outputs.semgrep_critical }}"
        HIGH_COUNT="${{ steps.semgrep_scan.outputs.semgrep_high }}"
        MEDIUM_COUNT="${{ steps.semgrep_scan.outputs.semgrep_medium }}"
        LOW_COUNT="${{ steps.semgrep_scan.outputs.semgrep_low }}"
        ESLINT_ERRORS="${{ steps.eslint_scan.outputs.eslint_errors }}"
        ESLINT_WARNINGS="${{ steps.eslint_scan.outputs.eslint_warnings }}"
        
        echo "## ðŸš¨ Web Stack Security Alert (MERN)" > issue_body.md
        echo "" >> issue_body.md
        echo "**Scan:** Backend Security (Semgrep + ESLint)" >> issue_body.md
        echo "**Severity:** HIGH/CRITICAL" >> issue_body.md
        echo "**Triggered by:** ${{ github.event_name }} on ${{ github.ref_name }}" >> issue_body.md
        echo "" >> issue_body.md
        echo "### ðŸ” Findings Summary" >> issue_body.md
        echo "" >> issue_body.md
        echo "#### Semgrep Results:" >> issue_body.md
        echo "- **CRITICAL:** $CRITICAL_COUNT" >> issue_body.md
        echo "- **HIGH:** $HIGH_COUNT" >> issue_body.md
        echo "- **MEDIUM:** $MEDIUM_COUNT" >> issue_body.md
        echo "- **LOW:** $LOW_COUNT" >> issue_body.md
        echo "" >> issue_body.md
        echo "#### ESLint Results:" >> issue_body.md
        echo "- **Errors:** $ESLINT_ERRORS" >> issue_body.md
        echo "- **Warnings:** $ESLINT_WARNINGS" >> issue_body.md
        echo "" >> issue_body.md
        
        # Add Semgrep HIGH/CRITICAL details
        if [[ "$CRITICAL_COUNT" -gt 0 ]] || [[ "$HIGH_COUNT" -gt 0 ]]; then
          echo "### ðŸ”´ Critical & High Severity Issues" >> issue_body.md
          echo '```' >> issue_body.md
          jq -r '.results[] | select(.extra.severity == "CRITICAL" or .extra.severity == "HIGH") | 
            "\(.extra.severity) - \(.path):\(.start.line)\n  Rule: \(.check_id)\n  Message: \(.extra.message)\n"' semgrep-report.json | head -n 100 >> issue_body.md
          echo '```' >> issue_body.md
        fi
        
        # Add ESLint errors
        if [[ "$ESLINT_ERRORS" -gt 0 ]]; then
          echo "" >> issue_body.md
          echo "### âš ï¸ ESLint Security Errors" >> issue_body.md
          echo '```' >> issue_body.md
          jq -r '.[] | select(.messages | length > 0) | .filePath as $file | 
            .messages[] | select(.severity == 2) | 
            "\($file):\(.line):\(.column) - \(.message) (\(.ruleId))"' eslint-report.json | head -n 50 >> issue_body.md
          echo '```' >> issue_body.md
        fi
        
        # Remediation
        echo "" >> issue_body.md
        echo "---" >> issue_body.md
        echo "### ðŸ› ï¸ Remediation Steps" >> issue_body.md
        echo "" >> issue_body.md
        echo "#### Frontend (React):" >> issue_body.md
        echo "1. **XSS Prevention:** Avoid \`dangerouslySetInnerHTML\`, sanitize user inputs" >> issue_body.md
        echo "2. **State Management:** Validate props, use PropTypes or TypeScript" >> issue_body.md
        echo "3. **API Calls:** Use HTTPS, validate responses, implement CSRF tokens" >> issue_body.md
        echo "" >> issue_body.md
        echo "#### Backend (Node.js/Express):" >> issue_body.md
        echo "1. **Input Validation:** Sanitize all inputs, use libraries like \`validator.js\`" >> issue_body.md
        echo "2. **SQL/NoSQL Injection:** Use parameterized queries, avoid string concatenation" >> issue_body.md
        echo "3. **Authentication:** Implement JWT properly, use \`bcrypt\` for passwords" >> issue_body.md
        echo "4. **Headers:** Install and configure \`helmet.js\` for security headers" >> issue_body.md
        echo "5. **Rate Limiting:** Use \`express-rate-limit\` to prevent abuse" >> issue_body.md
        echo "" >> issue_body.md
        echo "#### General:" >> issue_body.md
        echo "- Update all dependencies to latest secure versions" >> issue_body.md
        echo "- Review OWASP Top 10 guidelines" >> issue_body.md
        echo "- Implement security linting in pre-commit hooks" >> issue_body.md
        echo "" >> issue_body.md
        echo "**Workflow Run:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> issue_body.md
        
        # Check for existing open issue
        EXISTING_ISSUE=$(gh issue list --state open --search "Web Stack Security Alert in:title" --json number --jq '.[0].number' || true)
        
        if [[ -n "$EXISTING_ISSUE" ]]; then
          echo "âš ï¸ Updating existing issue #$EXISTING_ISSUE"
          gh issue comment "$EXISTING_ISSUE" --body "ðŸ”„ **Recurrence detected** in workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        else
          echo "ðŸš¨ Creating new security issue"
          gh issue create \
            --title "[HIGH/CRITICAL] Web Stack Security Alert - $CRITICAL_COUNT CRITICAL, $HIGH_COUNT HIGH" \
            --body-file issue_body.md \
            --label "security,backend,high-severity,MERN" \
            --assignee "${{ github.actor }}"
        fi

    - name: Fail Workflow Gate
      if: |
        inputs.fail_on_high_critical == 'true' && 
        (steps.semgrep_scan.outputs.semgrep_critical > 0 || steps.semgrep_scan.outputs.semgrep_high > 0)
      shell: bash
      run: |
        echo "::error::HIGH or CRITICAL backend security issues detected. Build failed."
        exit 1
