name: "Web Stack Security Scan (MERN)"
description: "Full-stack SAST for React (Frontend) and Node.js (Backend)."

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
    default: '${{ github.token }}'
  working-directory:
    description: 'Path to the source code'
    required: false
    default: '.'
  fail-build:
    description: "Fail if vulnerabilities are found"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Setup Node & Python
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Tools
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        npm install eslint eslint-plugin-security --no-save
        python3 -m pip install semgrep

    - name: Run ESLint Security
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        # Write header even if it fails
        echo "#### ðŸ” ESLint Security Findings" > ../eslint-report.md
        npx eslint . --plugin security --rule 'security/detect-object-injection: warn' --format markdown >> ../eslint-report.md || echo "No major ESLint issues." >> ../eslint-report.md

    - name: Run Semgrep (Full Stack)
      id: semgrep_run
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        # ADDED p/react and p/javascript for full frontend coverage
        echo '{"results": []}' > ../semgrep-report.json
        semgrep scan --config p/nodejs --config p/react --config p/javascript --config p/owasp-top-10 --json --output ../semgrep-report.json || true

    - name: ðŸ“Š Generate Job Summary
      id: generate_summary
      shell: bash
      run: |
        echo "### ðŸ›¡ï¸ Web Stack Security Report (MERN)" >> $GITHUB_STEP_SUMMARY
        
        # Safe JQ parsing
        VULN_COUNT=$(jq '.results | length' semgrep-report.json 2>/dev/null || echo "0")
        FOUND="false"

        if [ "$VULN_COUNT" -gt 0 ]; then
          echo "#### ðŸ›‘ Vulnerabilities Detected ($VULN_COUNT)" >> $GITHUB_STEP_SUMMARY
          echo "| Severity | Rule | File:Line | Message |" >> $GITHUB_STEP_SUMMARY
          echo "| :--- | :--- | :--- | :--- |" >> $GITHUB_STEP_SUMMARY
          jq -r '.results[] | "| \(.extra.severity) | \(.check_id) | \(.path):\(.start.line) | \(.extra.message | gsub("\n"; " ")) |"' semgrep-report.json >> $GITHUB_STEP_SUMMARY
          FOUND="true"
        else
          echo "âœ… **No high-risk semantic vulnerabilities detected.**" >> $GITHUB_STEP_SUMMARY
        fi
        
        echo "---" >> $GITHUB_STEP_SUMMARY
        [ -f eslint-report.md ] && cat eslint-report.md >> $GITHUB_STEP_SUMMARY
        echo "found_issues=$FOUND" >> $GITHUB_OUTPUT

    - name: ðŸš¨ Report Web Security Incident
      if: steps.generate_summary.outputs.found_issues == 'true'
      uses: Caladrius-Health-AI-Studio/github-actions/.github/actions/report-security-issue@main
      with:
        scan_name: "Web Stack Security"
        severity: "HIGH"
        finding_summary: "${{ steps.semgrep_run.outputs.vuln_count }} Web/API vulnerabilities detected."
        details_file_path: "semgrep-report.json"
        remediation_steps: |
          1. **Frontend:** Audit React components for `dangerouslySetInnerHTML`.
          2. **Backend:** Sanitize all SQL/NoSQL inputs.
          3. **Headers:** Ensure `helmet.js` is implemented in Express.

    - name: Fail Build Gate
      if: steps.generate_summary.outputs.found_issues == 'true' && inputs.fail-build == 'true'
      shell: bash
      run: |
        echo "::error::Web Security Scan Failed. Review the Job Summary for details."
        exit 1
