name: 'Non-Compliant Files Scan'
description: 'Scans for forbidden file types in Caladrius repos (executables, binaries, archives, etc.)'

inputs:
  fail_on_detection:
    description: 'Fail the workflow if forbidden files are detected'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Scan for Non-Compliant Files
      id: scan_files
      shell: bash
      run: |
        REPORT_FILE="${{ github.workspace }}/non_compliant_report.txt"
        touch "$REPORT_FILE"
        
        FOUND_NC=false
        TOTAL=0
        
        # Forbidden extensions
        FORBIDDEN_EXTS=("exe" "dll" "so" "dylib" "bin" "o" "a" "lib" "zip" "tar" "gz" "rar" "7z" "dmg" "pkg" "deb" "rpm")
        
        # Get changed files (PR or Push)
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          BASE_SHA="${{ github.event.pull_request.base.sha }}"
          git fetch origin "$BASE_SHA" --depth=1
          FILES=$(git diff --name-only --diff-filter=ACM "$BASE_SHA" HEAD)
        else
          if [[ "${{ github.event.before }}" != "0000000000000000000000000000000000000000" ]]; then
            FILES=$(git diff --name-only --diff-filter=ACM "${{ github.event.before }}" HEAD)
          else
            FILES=$(git ls-files)
          fi
        fi
        
        # Scan each file
        while IFS= read -r file; do
          [[ -z "$file" ]] && continue
          [[ ! -f "$file" ]] && continue
          
          filename=$(basename "$file")
          extension="${filename##*.}"
          
          # Check if extension is forbidden
          for forbidden in "${FORBIDDEN_EXTS[@]}"; do
            if [[ "$extension" == "$forbidden" ]]; then
              FOUND_NC=true
              echo "::error file=$file,line=0,title=Non-Compliant File Detected::File '$filename' is restricted in Caladrius repos."
              echo "- **$filename** (\`$file\`) - Extension: .$extension" >> "$REPORT_FILE"
              ((TOTAL++))
              break
            fi
          done
        done <<< "$FILES"
        
        echo "found_nc=$FOUND_NC" >> $GITHUB_OUTPUT
        echo "violation_count=$TOTAL" >> $GITHUB_OUTPUT

    - name: Write Summary Report
      if: always()
      shell: bash
      run: |
        REPORT_FILE="${{ github.workspace }}/non_compliant_report.txt"
        echo "## 🚫 Non-Compliant Files Report" >> $GITHUB_STEP_SUMMARY
        
        if [[ -s "$REPORT_FILE" ]]; then
          echo "### 🛑 Found ${{ steps.scan_files.outputs.violation_count }} forbidden file(s)" >> $GITHUB_STEP_SUMMARY
          cat "$REPORT_FILE" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Action Required:** Remove these files before merging." >> $GITHUB_STEP_SUMMARY
        else
          echo "✅ **Repo is clean. No forbidden file types detected.**" >> $GITHUB_STEP_SUMMARY
        fi

    - name: Fail Workflow Gate
      if: steps.scan_files.outputs.found_nc == 'true' && inputs.fail_on_detection == 'true'
      shell: bash
      run: |
        echo "::error::Non-compliant files detected. Build failed."
        exit 1
