name: 'Non-Compliant Files Check'
description: 'Scans commits for dangerous binaries, secrets, and large archives.'

inputs:
  github_token:
    description: 'GitHub token'
    required: true
    default: '${{ github.token }}'
  fail_on_detection:
    description: 'Fail workflow if files are found'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get Changed Files
      id: get_files
      shell: bash
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          BASE_SHA="${{ github.event.pull_request.base.sha }}"
          git fetch origin "$BASE_SHA" --depth=1
          git diff --name-only "$BASE_SHA" HEAD > files_changed.txt
        else
          if [[ "${{ github.event.before }}" != "0000000000000000000000000000000000000000" ]]; then
            BASE_SHA="${{ github.event.before }}"
          else
            BASE_SHA="HEAD^"
          fi
          git diff --name-only "$BASE_SHA" HEAD > files_changed.txt || git ls-files > files_changed.txt
        fi

    - name: Scan for Non-Compliant Files
      id: scan
      shell: bash
      run: |
        # 1. RULES
        EXT_BIN="exe|dll|bat|cmd|bin|msi|ps1|vbs|scr|class|jar|o|so|lib"
        EXT_SEC="pem|key|crt|cert|p12|pfx|env|config"
        EXT_DATA="db|sqlite|sql|mdb|accdb|iso|zip|tar|gz|rar|7z|dmg|vmdk|vdi"
        EXT_MEDIA="mp3|mp4|wav|avi|mkv"
        FORBIDDEN_PATTERN="\.(($EXT_BIN)|($EXT_SEC)|($EXT_DATA)|($EXT_MEDIA))$"

        # 2. EXCLUSIONS
        declare -a EXCLUDE_FILES=("example.env" "package.json" "package-lock.json" "yarn.lock")

        FOUND_ISSUES="false"
        COUNT=0
        touch non_compliant_report.txt

        # 3. SCANNING
        while IFS= read -r file; do
            if [ ! -f "$file" ]; then continue; fi
            
            SKIP=false
            for exc in "${EXCLUDE_FILES[@]}"; do
                if [[ "$file" == *"$exc" ]]; then SKIP=true; break; fi
            done
            if [[ "$SKIP" == "true" ]]; then continue; fi

            if echo "$file" | grep -iEq "$FORBIDDEN_PATTERN"; then
                # Annotations show up in the "Files Changed" tab
                echo "::error file=$file,title=Non-Compliant File Detected::File '$file' is restricted in Caladrius repos."
                echo "- $file" >> non_compliant_report.txt
                FOUND_ISSUES="true"
                ((COUNT++))
            fi
        done < files_changed.txt

        # 4. OUTPUTS (No exit 1 here!)
        echo "found_issues=$FOUND_ISSUES" >> $GITHUB_OUTPUT
        echo "count=$COUNT" >> $GITHUB_OUTPUT

    - name: Write Summary Report
      if: always()
      shell: bash
      run: |
        echo "## 🚫 Non-Compliant Files Report" >> $GITHUB_STEP_SUMMARY
        COUNT="${{ steps.scan.outputs.count }}"
        COUNT=${COUNT:-0}
        
        if [[ "$COUNT" -gt 0 ]]; then
            echo "### 🛑 Found $COUNT forbidden files" >> $GITHUB_STEP_SUMMARY
            echo "These files must be removed before merging to 'dev':" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            cat non_compliant_report.txt >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
        else
            echo "✅ **Repo is clean.** No forbidden file types detected." >> $GITHUB_STEP_SUMMARY
        fi

    - name: 🚨 Report Non-Compliant Files Incident
      if: steps.scan.outputs.found_issues == 'true'
      uses: Caladrius-Health-AI-Studio/github-actions/.github/actions/report-security-issue@main
      with:
        github_token: ${{ inputs.github_token }} 
        scan_name: "Non-Compliant Files"
        severity: "HIGH"
        finding_summary: "${{ steps.scan.outputs.count }} forbidden files detected."
        details_file_path: "non_compliant_report.txt"
        remediation_steps: |
          1. Delete the binaries/archives from the PR.
          2. Use .gitignore to block these extensions permanently.

    - name: Fail Workflow Gate
      if: steps.scan.outputs.found_issues == 'true' && inputs.fail_on_detection == 'true'
      shell: bash
      run: |
        echo "::error::Hygiene Gate Failed: Non-compliant files detected."
        exit 1
