name: "Gitleaks Secret Scan"
description: "Runs Gitleaks to scan for secrets and creates a summary/incident report if found."

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
    default: '${{ github.token }}'
  fail-build:
    description: "Fail if secrets are found"
    required: false
    default: "true"
  GITLEAKS_LICENSE:
    description: 'Gitleaks license key'
    required: false # Changed to false so open-source version doesn't crash if secret is missing

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Gitleaks
      shell: bash
      run: |
        GITLEAKS_VERSION="8.18.4"
        echo "Installing Gitleaks v$GITLEAKS_VERSION..."
        curl -sSfL "https://github.com/gitleaks/gitleaks/releases/download/v${GITLEAKS_VERSION}/gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz" | tar -xz
        chmod +x gitleaks
        sudo mv gitleaks /usr/local/bin/

    - name: Create Gitleaks config
      shell: bash
      run: |
        cat > gitleaks.toml << 'EOL'
        [allowlist]
        paths = [
          '''.*test.*''',
          '''.*tests.*''',
          '''.*/__tests__/.*''',
          '''.*/__test__/.*''',
          '''.*/test/.*''',
          '''.*/tests/.*''',
        ]
        EOL

    - name: Run Gitleaks scan
      id: gitleaks
      shell: bash
      env:
        GITLEAKS_LICENSE: ${{ inputs.GITLEAKS_LICENSE }}
      run: |
        echo "Starting scan..."
        touch gitleaks-report.json
        
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          gitleaks detect --source="." --log-opts="${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }}" --verbose --report-format json --report-path gitleaks-report.json -c gitleaks.toml || true
        else
          gitleaks detect --source="." --verbose --report-format json --report-path gitleaks-report.json -c gitleaks.toml || true
        fi

        # Check if report has content and isn't just an empty JSON array
        if [ -s "gitleaks-report.json" ] && [ "$(cat gitleaks-report.json)" != "[]" ]; then
          echo "secrets_found=true" >> $GITHUB_OUTPUT
          # Create a text-only summary for the incident report step
          jq -r '.[] | "File: \(.File) | Rule: \(.RuleID) | Commit: \(.Commit)"' gitleaks-report.json > gitleaks_summary.txt
        else
          echo "secrets_found=false" >> $GITHUB_OUTPUT
        fi

    - name: Write Summary Report
      if: always()
      shell: bash
      run: |
        echo "## 🔑 Gitleaks Secret Scan Summary" >> $GITHUB_STEP_SUMMARY
        if [[ "${{ steps.gitleaks.outputs.secrets_found }}" == "true" ]]; then
          echo "### 🛑 CRITICAL: Hardcoded Secrets Detected" >> $GITHUB_STEP_SUMMARY
          echo "| File | Secret Type | Commit |" >> $GITHUB_STEP_SUMMARY
          echo "| :--- | :--- | :--- |" >> $GITHUB_STEP_SUMMARY
          jq -r '.[] | "| \(.File) | \(.RuleID) | \(.Commit) |"' gitleaks-report.json >> $GITHUB_STEP_SUMMARY
        else
          echo "✅ **No secrets detected.**" >> $GITHUB_STEP_SUMMARY
        fi

    - name: 🚨 Report Secret Leak Incident
      if: steps.gitleaks.outputs.secrets_found == 'true'
      uses: Caladrius-Health-AI-Studio/github-actions/.github/actions/report-security-issue@main
      with:
        scan_name: "Gitleaks Secret Detection"
        severity: "CRITICAL"
        finding_summary: "Hardcoded credentials (API Key, Token, or Password) detected."
        details_file_path: "gitleaks_summary.txt"
        remediation_steps: |
          1. **Revoke Immediately:** The leaked secret is compromised. Rotate it.
          2. **Rewrite History:** Use `git filter-repo` to scrub the secret from history.
          3. **Do Not Just Delete:** A deletion commit leaves the secret in the Git history logs.

    - name: Fail Build Gate
      if: steps.gitleaks.outputs.secrets_found == 'true' && inputs.fail-build == 'true'
      shell: bash
      run: |
        echo "::error::Secret Scan Failed. Please rotate credentials and scrub history."
        exit 1
