name: 'Gitleaks Secret Scan'
description: 'Scans Git history for hardcoded secrets, API keys, tokens, and credentials'

inputs:
  fail_on_detection:
    description: 'Fail the workflow if secrets are detected'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Install Gitleaks
      shell: bash
      run: |
        wget -q https://github.com/gitleaks/gitleaks/releases/download/v8.18.2/gitleaks_8.18.2_linux_x64.tar.gz
        tar -xzf gitleaks_8.18.2_linux_x64.tar.gz
        sudo mv gitleaks /usr/local/bin/
        rm gitleaks_8.18.2_linux_x64.tar.gz

    - name: Run Gitleaks Scan
      id: gitleaks_scan
      shell: bash
      run: |
        REPORT_FILE="${{ github.workspace }}/gitleaks-report.json"
        
        # Run Gitleaks (exit code 1 = leaks found, but we catch it)
        if gitleaks detect --source . --report-path "$REPORT_FILE" --report-format json --verbose; then
          echo "found_secrets=false" >> $GITHUB_OUTPUT
          echo "secret_count=0" >> $GITHUB_OUTPUT
          # Create empty report if none exists
          echo '{"results":[]}' > "$REPORT_FILE"
        else
          # Secrets found
          SECRET_COUNT=$(jq '.[] | length' "$REPORT_FILE" 2>/dev/null || echo "0")
          echo "found_secrets=true" >> $GITHUB_OUTPUT
          echo "secret_count=$SECRET_COUNT" >> $GITHUB_OUTPUT
          
          # Add GitHub annotations
          jq -r '.[] | "::error file=\(.File),line=\(.StartLine),title=Secret Detected::\(.Description) - \(.RuleID)"' "$REPORT_FILE" || true
        fi

    - name: Write Summary Report
      if: always()
      shell: bash
      run: |
        REPORT_FILE="${{ github.workspace }}/gitleaks-report.json"
        echo "## 🔑 Gitleaks Secret Scan Summary" >> $GITHUB_STEP_SUMMARY
        
        if [[ "${{ steps.gitleaks_scan.outputs.found_secrets }}" == "true" ]]; then
          echo "### 🛑 Found ${{ steps.gitleaks_scan.outputs.secret_count }} secret(s)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| File | Line | Secret Type | Commit |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- | --- | --- |" >> $GITHUB_STEP_SUMMARY
          jq -r '.[] | "| \(.File) | \(.StartLine) | \(.RuleID) | \(.Commit[:7]) |"' "$REPORT_FILE" >> $GITHUB_STEP_SUMMARY || true
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Action Required:** Rotate exposed secrets immediately and scrub from Git history." >> $GITHUB_STEP_SUMMARY
        else
          echo "✅ **No secrets detected.**" >> $GITHUB_STEP_SUMMARY
        fi

    - name: Fail Workflow Gate
      if: steps.gitleaks_scan.outputs.found_secrets == 'true' && inputs.fail_on_detection == 'true'
      shell: bash
      run: |
        echo "::error::Secrets detected in Git history. Build failed."
        exit 1
